apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: python-sample
  namespace: pipelines-demo
spec:
  params:
  - name: gitrevision
    value: $(body.after)
  - name: gitrepositoryurl
    value: $(body.repository.html_url)
