name: CI/CD with RHACS Scan

on:
  push:
    branches: ["main"]

env:
  IMAGE_NAME: quayadmin/pipeline-demo
  IMAGE_TAG: latest
  REGISTRY: innovative-quay-quay-registry.apps.parth-rosa-acm.4h5l.p1.openshiftapps.com

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Quay.io
      uses: docker/login-action@v2
      with:
        registry: $REGISTRY
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
    
    - name: Install roxctl
      uses: stackrox/roxctl-installer-action@v1.1.3

    - name: Scan image using RHACS
      env:
        ROX_API_TOKEN: ${{ secrets.ROX_API_TOKEN }}
        ROX_CENTRAL_HOST: ${{ secrets.ROX_CENTRAL_HOST }}
      run: |
        roxctl image scan \
          --output=table \
          --endpoint "$ROX_CENTRAL_HOST" \
          --insecure-skip-tls-verify \
          --image "$REGISTRY/$IMAGE_NAME:$IMAGE_TAG"
          
    - name: Check image using RHACS
      env:
        ROX_API_TOKEN: ${{ secrets.ROX_API_TOKEN }}
        ROX_CENTRAL_HOST: ${{ secrets.ROX_CENTRAL_HOST }}
      run: |
        roxctl image check \
          --output=table \
          --endpoint "$ROX_CENTRAL_HOST" \
          --insecure-skip-tls-verify \
          --image "$REGISTRY/$IMAGE_NAME:$IMAGE_TAG"
    - name: Deployment check using RHACS
      env:
        ROX_API_TOKEN: ${{ secrets.ROX_API_TOKEN }}
        ROX_CENTRAL_HOST: ${{ secrets.ROX_CENTRAL_HOST }}
      run: |
        roxctl deployment check \
          --output=table \
          --endpoint "$ROX_CENTRAL_HOST" \
          --insecure-skip-tls-verify \
          --file=./k8s/deployment.yaml
  

    - name: Push Docker image
      run: |
        docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG